### ISSUE TITLE
mysql 5.7及以上的版本运行table.sql会报错

### ISSUE THREAD

**Issue by dislazy** [baidu/brcc#14]

**Comment by ghzengqy568** [comment]
> _No description provided._

能给一下错误信息吗?

**Comment by dislazy** [comment]
是由于建表时日期默认0000-00-00 00:00:00 导致的，改成CURRENT_TIMESTAMP 即可

**Comment by ghzengqy568** [comment]
> 是由于建表时日期默认0000-00-00 00:00:00 导致的，改成CURRENT_TIMESTAMP 即可

我在Server version: 5.7.30 MySQL Community Server (GPL)版本上试了没有报错， 你那边能把错误信息贴一下吗？

**Comment by dislazy** [comment]
理解了，如果说需要强制要求将数据修改为0000-00-00 00:00:00 而去修改数据库的SQL_MODE,是不是不够合理呢，使用CURRENT_TIMESTAMP是不是能避免去做这种规范性质的改动呢

**Comment by ghzengqy568** [comment]
> 理解了，如果说需要强制要求将数据修改为0000-00-00 00:00:00 而去修改数据库的SQL_MODE,是不是不够合理呢，使用CURRENT_TIMESTAMP是不是能避免去做这种规范性质的改动呢

是的，对应update_time, create_time 用CURRENT_TIMESTAMP比较合适， 但是我们还有其他一些场景可能不太适合CURRENT_TIMESTAMP， 我们代码中已经保障了时间设置， 我们将 default '0000-00-00 00:00' 去掉吧， 避免SQL_MODE不支持的情况发生
