### ISSUE TITLE
测试账号无法登录

### ISSUE THREAD

**Issue by xiaoxue201711** [baidu/brcc#164]
![image](https://user-images.githubusercontent.com/33747516/153139168-7a52d565-1287-4f0b-afe8-835c5cf0848b.png)

**Comment by aroundpie** [comment]
已解决

**Comment by aroundpie** [comment]
> ![image](https://user-images.githubusercontent.com/33747516/153139168-7a52d565-1287-4f0b-afe8-835c5cf0848b.png)

已解决
