### ISSUE TITLE
安装脚本的数据库表默认时间格式'0000-00-00 00:00:00'报错

### ISSUE THREAD

**Issue by vinyeah** [baidu/brcc#19]
安装时候数据库表时间字段默认值用的是'0000-00-00 00:00:00'的格式，再我这mysql版本上认为格式错误，手工改为"1970-01-01 00:00:00'解决

**Comment by dislazy** [comment]
之前针对这个提过相关issue，刚刚提了pr修复这个文件  可以见 https://github.com/baidu/brcc/issues/14
