### ISSUE TITLE
管理端操作有错误

### ISSUE THREAD

**Issue by krisjin** [baidu/brcc#2]
不能创建产品线，有乱码

**Comment by zhangliang1024** [comment]
使用默认部署方式，会存在用户权限问题。乱码是错误提示

**Comment by ghzengqy568** [comment]
> 不能创建产品线，有乱码

请问是以管理员的身份操作的吗？能否在chrome浏览器的开发者工具的network中看看是哪个接口报错的， 错误码是多少？

**Comment by ghzengqy568** [comment]
> 不能创建产品线，有乱码

之前提供的初始化数据 doc/database/data.sql 有误， 我们修正后重新上传，已安装的可以通过下面的sql修复一下

**Comment by krisjin** [comment]
> > 不能创建产品线，有乱码
> 
> 之前提供的初始化数据 doc/database/data.sql 有误， 我们修正后重新上传，已安装的可以通过下面步骤修复
> 
> 1. 执行sql
>    use brcc;
>    update `rcc_user` set `status` = 0 , `role` = 3 where `name` = 'admin';
> 2. 清理redis缓存
>    查寻用户对应的key
>    keys mapp.rcc.string.usertoken.*
>    删除缓存
>    del [上面查下出来的KEY]

是的，用admin/admin登陆的，执行那个sql就好了

**Comment by ghzengqy568** [comment]
tag 1.0.1已经修复以上问题
